//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 09:59:48 PM GMT 
//


package com.company.myloyal;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.company.myloyal package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.company.myloyal
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link Booking.CostSummary }
     * 
     */
    public Booking.CostSummary createBookingCostSummary() {
        return new Booking.CostSummary();
    }

    /**
     * Create an instance of {@link Booking.Journey }
     * 
     */
    public Booking.Journey createBookingJourney() {
        return new Booking.Journey();
    }

    /**
     * Create an instance of {@link RetrieveCustomerBookingsResponse }
     * 
     */
    public RetrieveCustomerBookingsResponse createRetrieveCustomerBookingsResponse() {
        return new RetrieveCustomerBookingsResponse();
    }

    /**
     * Create an instance of {@link BookingList }
     * 
     */
    public BookingList createBookingList() {
        return new BookingList();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link RetrieveCustomerBookings }
     * 
     */
    public RetrieveCustomerBookings createRetrieveCustomerBookings() {
        return new RetrieveCustomerBookings();
    }

    /**
     * Create an instance of {@link RetrieveCustomerLoyaltyPointsResponse }
     * 
     */
    public RetrieveCustomerLoyaltyPointsResponse createRetrieveCustomerLoyaltyPointsResponse() {
        return new RetrieveCustomerLoyaltyPointsResponse();
    }

    /**
     * Create an instance of {@link LoyaltyPointsList }
     * 
     */
    public LoyaltyPointsList createLoyaltyPointsList() {
        return new LoyaltyPointsList();
    }

    /**
     * Create an instance of {@link GetCustomerProfileDataResponse }
     * 
     */
    public GetCustomerProfileDataResponse createGetCustomerProfileDataResponse() {
        return new GetCustomerProfileDataResponse();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link SearchCustomerBookingsResponse }
     * 
     */
    public SearchCustomerBookingsResponse createSearchCustomerBookingsResponse() {
        return new SearchCustomerBookingsResponse();
    }

    /**
     * Create an instance of {@link GetCustomerProfileData }
     * 
     */
    public GetCustomerProfileData createGetCustomerProfileData() {
        return new GetCustomerProfileData();
    }

    /**
     * Create an instance of {@link RetrieveCustomerLoyaltyPoints }
     * 
     */
    public RetrieveCustomerLoyaltyPoints createRetrieveCustomerLoyaltyPoints() {
        return new RetrieveCustomerLoyaltyPoints();
    }

    /**
     * Create an instance of {@link SearchCustomerBookings }
     * 
     */
    public SearchCustomerBookings createSearchCustomerBookings() {
        return new SearchCustomerBookings();
    }

    /**
     * Create an instance of {@link LoyaltyPoints }
     * 
     */
    public LoyaltyPoints createLoyaltyPoints() {
        return new LoyaltyPoints();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Telephone }
     * 
     */
    public Telephone createTelephone() {
        return new Telephone();
    }

    /**
     * Create an instance of {@link Booking.Passenger }
     * 
     */
    public Booking.Passenger createBookingPassenger() {
        return new Booking.Passenger();
    }

    /**
     * Create an instance of {@link Booking.Extra }
     * 
     */
    public Booking.Extra createBookingExtra() {
        return new Booking.Extra();
    }

    /**
     * Create an instance of {@link Booking.CostSummary.CostingItem }
     * 
     */
    public Booking.CostSummary.CostingItem createBookingCostSummaryCostingItem() {
        return new Booking.CostSummary.CostingItem();
    }

    /**
     * Create an instance of {@link Booking.Journey.Leg }
     * 
     */
    public Booking.Journey.Leg createBookingJourneyLeg() {
        return new Booking.Journey.Leg();
    }

    /**
     * Create an instance of {@link Booking.Journey.Carrier }
     * 
     */
    public Booking.Journey.Carrier createBookingJourneyCarrier() {
        return new Booking.Journey.Carrier();
    }

}
